In [ ]:
!pip install ijson

Collecting ijson
  Downloading ijson-3.4.0.post0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Downloading ijson-3.4.0.post0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (149 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.0/149.0 kB 6.2 MB/s eta 0:00:00
Installing collected packages: ijson
Successfully installed ijson-3.4.0.post0

In [ ]:
import pandas as pd

In [ ]:
#json muy pesado ijson para poedr seleccionar alas filas
import ijson

with open("user.json", "rb") as f:
    objects = ijson.items(f, "item")
    first_user = next(objects)

print(first_user.keys())

dict_keys(['created_at', 'description', 'entities', 'id', 'location', 'name', 'pinned_tweet_id', 'profile_image_url', 'protected', 'public_metrics', 'url', 'username', 'verified', 'withheld'])

In [ ]:
#i para la cantidad de filas a traer
import ijson

users1 = []

with open("user.json", "rb") as f:
    for i, user1 in enumerate(ijson.items(f, "item")):
        if i ==50000:
            break
        users1.append(user1)

len(users1)

50000

In [ ]:


df = pd.DataFrame(users1)
df.head()

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld
0,2020-01-16 02:02:55+00:00,Theoretical Computer Scientist. See also https...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1217628182611927040,"Cambridge, MA",Boaz Barak,NaN,https://pbs.twimg.com/profile_images/125226236...,False,"{'followers_count': 7316, 'following_count': 2...",https://t.co/BoMip9FF17,boazbaraktcs,False,None
1,2014-07-02 17:56:46+00:00,creative _,None,u2664730894,🎈,olawale 💨,NaN,https://pbs.twimg.com/profile_images/147837638...,False,"{'followers_count': 123, 'following_count': 10...",,wale_io,False,None
2,2020-05-30 12:10:45+00:00,👽,None,u1266703520205549568,None,panagiota_.b,NaN,https://pbs.twimg.com/profile_images/142608606...,False,"{'followers_count': 3, 'following_count': 62, ...",,b_panagiota,False,None
3,2019-01-26 13:52:49+00:00,mama to maya. ABIM research pathway fellow @UV...,"{'description': {'mentions': [{'start': 43, 'e...",u1089159225148882949,"Charlottesville, VA","Jacqueline Hodges, MD MPH",NaN,https://pbs.twimg.com/profile_images/130229171...,False,"{'followers_count': 350, 'following_count': 57...",,jachodges_md,False,None
4,2009-04-30 19:01:42+00:00,Father / SWT Alumnus / Longhorn Fan,None,u36741729,United States,Matthew Stubblefield,NaN,https://pbs.twimg.com/profile_images/145808462...,True,"{'followers_count': 240, 'following_count': 29...",,Matthew_Brody,False,None

In [ ]:
#parse para transformar la columna public metrics en columnas
import ast
import pandas as pd

def parse_public_metrics(x):
    if isinstance(x, dict):
        return x
    if isinstance(x, str) and x.strip() != "":
        return ast.literal_eval(x)
    return {}

df["public_metrics"] = df["public_metrics"].apply(parse_public_metrics)

In [ ]:
metrics_df = df["public_metrics"].apply(pd.Series)

In [ ]:
len(metrics_df)

50000

In [ ]:
#une la columna public metric con el resto de la tabla
df = pd.concat([df.drop(columns=["public_metrics"]), metrics_df], axis=1)

In [ ]:
df.head()

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,url,username,verified,withheld,followers_count,following_count,tweet_count,listed_count
0,2020-01-16 02:02:55+00:00,Theoretical Computer Scientist. See also https...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1217628182611927040,"Cambridge, MA",Boaz Barak,NaN,https://pbs.twimg.com/profile_images/125226236...,False,https://t.co/BoMip9FF17,boazbaraktcs,False,None,7316,215,3098,69
1,2014-07-02 17:56:46+00:00,creative _,None,u2664730894,🎈,olawale 💨,NaN,https://pbs.twimg.com/profile_images/147837638...,False,,wale_io,False,None,123,1090,1823,0
2,2020-05-30 12:10:45+00:00,👽,None,u1266703520205549568,None,panagiota_.b,NaN,https://pbs.twimg.com/profile_images/142608606...,False,,b_panagiota,False,None,3,62,66,0
3,2019-01-26 13:52:49+00:00,mama to maya. ABIM research pathway fellow @UV...,"{'description': {'mentions': [{'start': 43, 'e...",u1089159225148882949,"Charlottesville, VA","Jacqueline Hodges, MD MPH",NaN,https://pbs.twimg.com/profile_images/130229171...,False,,jachodges_md,False,None,350,577,237,1
4,2009-04-30 19:01:42+00:00,Father / SWT Alumnus / Longhorn Fan,None,u36741729,United States,Matthew Stubblefield,NaN,https://pbs.twimg.com/profile_images/145808462...,True,,Matthew_Brody,False,None,240,297,3713,8

In [ ]:
df[[
    "followers_count",
    "following_count",
    "tweet_count",
    "listed_count"
]].head(1001)

      followers_count  following_count  tweet_count  listed_count
0                7316              215         3098            69
1                 123             1090         1823             0
2                   3               62           66             0
3                 350              577          237             1
4                 240              297         3713             8
...               ...              ...          ...           ...
996                22             1013            5             1
997               589              730         5219             8
998              1199             4927         3674            27
999                55               19          280             1
1000           464651             1354        14066          1633

[1001 rows x 4 columns]

In [ ]:
label =pd.read_csv("label.csv")

In [ ]:
label.head(10010)

                         id  label
0      u1217628182611927040  human
1               u2664730894  human
2      u1266703520205549568  human
3      u1089159225148882949  human
4                 u36741729    bot
...                     ...    ...
10005           u1480520209  human
10006            u588901446  human
10007   u966249800919236608  human
10008            u376403603  human
10009            u443288053  human

[10010 rows x 2 columns]

In [ ]:
df2 = pd.merge(df, label, on='id', how='left')

In [ ]:
len(df2)

50000

In [ ]:
label_percentages = df2['label'].value_counts(normalize=True) * 100
display(label_percentages)

label
human    93.296
bot       6.704
Name: proportion, dtype: float64

In [ ]:
#lo mismo pero random
import ijson
import random

k = 100000
users = []

with open("user.json", "rb") as f:
    for i, user in enumerate(ijson.items(f, "item")):
        if i < k:
            users.append(user)
        else:
            j = random.randint(0, i)
            if j < k:
                users[j] = user

len(users)
dfrand = pd.DataFrame(users)

In [ ]:
#lo mismo pero radom
import ast
import pandas as pd

def parse_public_metrics(x):
    if isinstance(x, dict):
        return x
    if isinstance(x, str) and x.strip() != "":
        return ast.literal_eval(x)
    return {}

dfrand["public_metrics"] = dfrand["public_metrics"].apply(parse_public_metrics)
metrics_dfrand = dfrand["public_metrics"].apply(pd.Series)
dfrand = pd.concat([dfrand.drop(columns=["public_metrics"]), metrics_dfrand], axis=1)
df2rand = pd.merge(dfrand, label, on='id', how='left')

In [ ]:
df2rand.head()

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,url,username,verified,withheld,followers_count,following_count,tweet_count,listed_count,label
0,2018-10-04 14:50:09+00:00,"Insomnibat. Alopecia Universalis. Aquarian, fi...","{'description': {'hashtags': [{'start': 85, 'e...",u1047861437845184512,An Orchard SELondon,Heather The Fruit Bat💙,NaN,https://pbs.twimg.com/profile_images/123302372...,False,,TubbyBats,False,None,732,1800,19944,5,human
1,2020-07-07 18:33:10+00:00,Focus Instructional Coach,None,u1280570479309475850,"Massachusetts, USA",Lisa CARIGNAN,NaN,https://pbs.twimg.com/profile_images/128057174...,False,,Lisacarignan4,False,None,67,291,85,3,bot
2,2021-01-31 07:33:15+00:00,"Anestesista holistico,respetuoso,mamífero. Dou...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1355781143967236097,"Planeta Parto, Yukei",Juan Antonio 1mm3lm4n on the run account,1.363596e+18,https://pbs.twimg.com/profile_images/147940777...,False,https://t.co/tjZKABDnkK,pilotochungo1,False,None,3731,1331,30053,12,human
3,2016-06-03 09:27:04+00:00,,None,u738663280986710016,"Montréal, Québec",Edward Fon,NaN,https://abs.twimg.com/sticky/default_profile_i...,False,,TedfonMNI,False,None,71,31,58,2,bot
4,2017-06-27 08:58:34+00:00,Independent Power Producer. 100% renewable ene...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u879624986180308992,"Paris, France",NEOEN,NaN,https://pbs.twimg.com/profile_images/936269273...,False,https://t.co/j0ZnA0TqXq,NEOEN_Energy,False,None,1957,66,245,40,bot

In [ ]:
label_percentages = df2rand['label'].value_counts(normalize=True) * 100
display(label_percentages)

label
human    85.847
bot      14.153
Name: proportion, dtype: float64

In [ ]:
df2rand.shape

(100000, 18)

In [ ]:
df2rand.columns

Index(['created_at', 'description', 'entities', 'id', 'location', 'name',
       'pinned_tweet_id', 'profile_image_url', 'protected', 'url', 'username',
       'verified', 'withheld', 'followers_count', 'following_count',
       'tweet_count', 'listed_count', 'label'],
      dtype='object')

In [ ]:
df2rand.describe()

,pinned_tweet_id,followers_count,following_count,tweet_count,listed_count
count,3.895100e+04,1.000000e+05,1.000000e+05,1.000000e+05,100000.00000
mean,1.330837e+18,4.174403e+04,2.196341e+03,2.215120e+04,177.90797
std,2.080778e+17,5.953778e+05,1.321792e+04,2.625884e+05,1661.74263
min,6.091000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.00000
25%,1.273866e+18,1.550000e+02,2.070000e+02,3.570000e+02,1.00000
50%,1.415720e+18,9.160000e+02,6.340000e+02,3.117000e+03,9.00000
75%,1.473273e+18,4.936000e+03,1.689000e+03,1.536700e+04,73.00000
max,1.503448e+18,5.583014e+07,1.432905e+06,8.020813e+07,353106.00000

In [ ]:
df2rand.dtypes

created_at            object
description           object
entities              object
id                    object
location              object
name                  object
pinned_tweet_id      float64
profile_image_url     object
protected               bool
url                   object
username              object
verified                bool
withheld              object
followers_count        int64
following_count        int64
tweet_count            int64
listed_count           int64
label                 object
dtype: object

In [ ]:
len(df2rand)

100000

In [ ]:
num_columns = df2rand.shape[1]
display(num_columns)

18

In [ ]:
df2rand.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   created_at         100000 non-null  object
 1   description        100000 non-null  object
 2   entities           62872 non-null   object
 3   id                 100000 non-null  object
 4   location           70782 non-null   object
 5   name               100000 non-null  object
 6   pinned_tweet_id    38951 non-null   float64
 7   profile_image_url  100000 non-null  object
 8   protected          100000 non-null  bool
 9   url                100000 non-null  object
 10  username           100000 non-null  object
 11  verified           100000 non-null  bool
 12  withheld           7 non-null       object
 13  followers_count    100000 non-null  int64
 14  following_count    100000 non-null  int64
 15  tweet_count        100000 non-null  int64
 16  listed_count       100000 non-null  int64
 17  label              100000 non-null  object
dtypes: bool(2), float64(1), int64(4), object(11)
memory usage: 12.4+ MB

In [ ]:
list =pd.read_json("list.json")
list.tail()

,id,name,created_at,description,follower_count,member_count,private,owner_id
21865,l863566424375209984,Deep learning,2017-05-14 01:27:34+00:00,None,0,0,False,107770718
21866,l10667576,divulgacion & educacion,2010-04-16 10:03:29+00:00,None,29,373,False,29024460
21867,l90172505,Post Graphics Staff,2013-05-23 15:20:46+00:00,The visual journalists who work in The Washing...,67,32,False,87968068
21868,l702528800886648832,General science,2016-02-24 16:21:33+00:00,None,0,4,False,19732234
21869,l4148867,VancouverDrupal,2009-12-03 01:19:09+00:00,Vancouver Drupal Users,5,42,False,14117658

In [ ]:
hashtag =pd.read_json("hashtag.json")
hashtag.tail()

               id           tag_name
5146284  h5146284          ecase2019
5146285  h5146285  HealthMetrics2019
5146286  h5146286       whatshotinit
5146287  h5146287          TechThurs
5146288  h5146288    AustralianBanks

In [ ]:
list =pd.read_json("drive/MyDrive/Colab Notebooks/list.json")
list.tail()

,id,name,created_at,description,follower_count,member_count,private,owner_id
21865,l863566424375209984,Deep learning,2017-05-14 01:27:34+00:00,None,0,0,False,107770718
21866,l10667576,divulgacion & educacion,2010-04-16 10:03:29+00:00,None,29,373,False,29024460
21867,l90172505,Post Graphics Staff,2013-05-23 15:20:46+00:00,The visual journalists who work in The Washing...,67,32,False,87968068
21868,l702528800886648832,General science,2016-02-24 16:21:33+00:00,None,0,4,False,19732234
21869,l4148867,VancouverDrupal,2009-12-03 01:19:09+00:00,Vancouver Drupal Users,5,42,False,14117658

In [ ]:
import ijson
import random
import pandas as pd

k = 1300000
users = []

with open("/content/drive/MyDrive/Colab Notebooks/tweet_0.json", "rb") as f:
    for i, user in enumerate(ijson.items(f, "item")):

        if i < k:
            users.append(user)
        else:
            j = random.randint(0, i)
            if j < k:
                users[j] = user

dftweet = pd.DataFrame(users)
print(len(dftweet))

1300000

In [ ]:
dftweet.head()

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,possibly_sensitive,public_metrics,referenced_tweets,reply_settings,source,text,withheld
0,None,296854436,None,885726815397924864,2017-07-14 05:05:03+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t885726815397924864,NaN,es,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",So meta https://t.co/8UKMKyxUSK,None
1,None,272384813,None,1492800364793503744,2022-02-13 09:58:36+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492800364793503744,NaN,en,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/android"" ...",Any of my tweeps see Claire Welles at the trad...,None
2,None,468927016,None,1462813623798087687,2021-11-22 16:02:00+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1462813623798087687,NaN,en,False,"{'retweet_count': 4, 'reply_count': None, 'lik...",None,None,"<a href=""https://about.twitter.com/products/tw...",New content online: Efficient solid-state phot...,None
3,None,704124952052703232,None,1164983267793047552,2019-08-23 19:30:30+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1164983267793047552,NaN,en,False,"{'retweet_count': 1, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",From FBU to SWE — My Journey of Proving Myself...,None
4,None,453361268,None,1401918846802534409,2021-06-07 15:07:54+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1401918846802534409,NaN,en,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",Differentiable physics models makes model-base...,None

In [ ]:
dftweet.to_json("tweet1.json")

In [ ]:
#lo mismo pero radom
import ast
import pandas as pd

def parse_public_metrics(x):
    if isinstance(x, dict):
        return x
    if isinstance(x, str) and x.strip() != "":
        return ast.literal_eval(x)
    return {}

dftweet["public_metrics"] = dftweet["public_metrics"].apply(parse_public_metrics)
metrics_dftweet = dftweet["public_metrics"].apply(pd.Series)
dftweet = pd.concat([dftweet.drop(columns=["public_metrics"]), metrics_dftweet], axis=1)
dftweet["entities"] = dftweet["entities"].apply(parse_public_metrics)
entities_dftweet = dftweet["entities"].apply(pd.Series)
dftweet = pd.concat([dftweet.drop(columns=["entities"]), entities_dftweet], axis=1)

In [ ]:
dftweet["urls"] = dftweet["urls"].apply(parse_public_metrics)
urls_dftweet = dftweet["urls"].apply(pd.Series)
dftweet = pd.concat([dftweet.drop(columns=["urls"]), urls_dftweet], axis=1)

In [ ]:
entities_dftweet.head()

,hashtags,symbols,user_mentions,urls,media
0,[],[],"[{'screen_name': 'uwcse', 'name': 'Allen Schoo...",[],"[{'id': 1402592115582849035, 'id_str': '140259..."
1,[],[],"[{'screen_name': 'CarolineLessar8', 'name': 'C...",[],NaN
2,[],[],[],[],NaN
3,[],[],[],[],"[{'id': 1492939215667089411, 'id_str': '149293..."
4,[],[],[],"[{'url': 'https://t.co/s4eW9LpfEl', 'expanded_...",NaN

In [ ]:
metrics_dftweet.head()

   retweet_count  reply_count  like_count  quote_count
0            9.0          NaN        66.0          NaN
1           71.0          NaN         0.0          NaN
2          344.0          NaN      2465.0          NaN
3          239.0          NaN      1243.0          NaN
4            0.0          NaN         3.0          NaN

In [ ]:
dftweet.head()

,attachments,author_id,context_annotations,conversation_id,created_at,geo,id,in_reply_to_user_id,lang,possibly_sensitive,...,text,withheld,retweet_count,reply_count,like_count,quote_count,hashtags,symbols,user_mentions,media
0,None,807515,None,1402593409433358342,2021-06-09 11:48:22+00:00,None,t1402593409433358342,NaN,en,False,...,"Today, our @uwcse physcomp undergrads present ...",None,9.0,NaN,66.0,NaN,[],[],"[{'screen_name': 'uwcse', 'name': 'Allen Schoo...","[{'id': 1402592115582849035, 'id_str': '140259..."
1,None,59947704,None,1496253404464746498,2022-02-22 22:39:45+00:00,None,t1496253404464746498,NaN,fr,False,...,RT @CarolineLessar8: « Whoa Harris vient de co...,None,71.0,NaN,0.0,NaN,[],[],"[{'screen_name': 'CarolineLessar8', 'name': 'C...",NaN
2,None,17718887,None,1486162880588177410,2022-01-26 02:23:36+00:00,None,t1486162880588177410,NaN,en,False,...,STOP TESTING YOUR CHILDREN WITH MILD COLD SYMP...,None,344.0,NaN,2465.0,NaN,[],[],[],NaN
3,None,1204387229679980548,None,1492939242934255617,2022-02-13 19:10:27+00:00,None,t1492939242934255617,NaN,und,False,...,https://t.co/OjG0j1ZMWu,None,239.0,NaN,1243.0,NaN,[],[],[],"[{'id': 1492939215667089411, 'id_str': '149293..."
4,None,93898431,None,1496863751412371456,2022-02-24 15:05:03+00:00,None,t1496863751412371456,NaN,fr,False,...,Des footballeurs brésiliens demandent à être é...,None,0.0,NaN,3.0,NaN,[],[],[],NaN

In [ ]:
#agregando una columna con el days variance
sortby_followers = df2rand.sort_values(by="created_at", ascending=False)
sortby_followers["created_at"] = pd.to_datetime(sortby_followers["created_at"])
sortby_followers["Cutoverdate"] = pd.to_datetime("2022-04-01", utc=True) # Make Cutoverdate timezone-aware (UTC)
sortby_followers["days_variance"]=(sortby_followers["Cutoverdate"]-sortby_followers["created_at"]).dt.days
sortby_followers.head()

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,url,username,verified,withheld,followers_count,following_count,tweet_count,listed_count,label,Cutoverdate,days_variance
30591,2022-03-14 02:30:22+00:00,,None,u1503196765557829639,None,Adriana,NaN,https://abs.twimg.com/sticky/default_profile_i...,False,,Adriana06744405,False,None,0,1,0,0,bot,2022-04-01 00:00:00+00:00,17
1545,2022-03-13 09:34:48+00:00,,None,u1502941191549390852,"Bengaluru, India",Amal PS,NaN,https://pbs.twimg.com/profile_images/150294173...,False,,wonderboy708,False,None,1,22,0,0,human,2022-04-01 00:00:00+00:00,18
88210,2022-03-13 09:31:18+00:00,,None,u1502940273273614339,None,Sarfraz Malik,NaN,https://pbs.twimg.com/profile_images/150294035...,False,,Sarfraz79921156,False,None,0,0,0,0,bot,2022-04-01 00:00:00+00:00,18
98276,2022-03-13 01:33:57+00:00,Social Boy😉🧢📱💙,None,u1502820136746721281,None,Ojima,NaN,https://abs.twimg.com/sticky/default_profile_i...,False,,Ojima56341057,False,None,0,0,0,0,bot,2022-04-01 00:00:00+00:00,18
47208,2022-03-12 23:25:33+00:00,,None,u1502787897791254529,None,Phan Quế Anh,NaN,https://pbs.twimg.com/profile_images/150278818...,False,,PhanQuAnh5,False,None,0,0,0,0,human,2022-04-01 00:00:00+00:00,19

In [ ]:
Final_df = sortby_followers['id','tweet_count', 'followers_count', 'following_count',  'location', 'name', 'pinned_tweet_id', 'profile_image_url', 'protected', 'public_metrics', 'url', 'username', 'verified', 'withheld']

In [ ]:
import pandas as pd
dftweet =pd.read_json("tweet_8.json")
dftweet.tail()

In [ ]:
d.tail()

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,possibly_sensitive,public_metrics,referenced_tweets,reply_settings,source,text,withheld
999995,NaN,48377323,NaN,1479141793094643721,2022-01-06 17:24:19+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1479141793094643721,NaN,en,False,"{'retweet_count': 10, 'reply_count': None, 'li...",NaN,NaN,"<a href=""https://about.twitter.com/products/tw...",Updated blog with latest forecast snow amounts...,NaN
999996,NaN,558040899,NaN,1494662869857628160,2022-02-18 13:19:32+00:00,"{'hashtags': [{'text': 'Olympics2022', 'indice...",None,t1494662869857628160,NaN,en,False,"{'retweet_count': 12, 'reply_count': None, 'li...",NaN,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",Opinion | Olympic winners and losers \n#Olympi...,NaN
999997,NaN,30370614,NaN,949051638379106311,2018-01-04 22:55:17+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t949051638379106311,NaN,en,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",NaN,NaN,"<a href=""http://twitter.com/download/iphone"" r...",Oh my!!!\n https://t.co/rDwxgwstmS,NaN
999998,NaN,1238768663555182593,NaN,1494792149925257217,2022-02-18 21:53:15+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1494792149925257217,421509774.0,fr,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",NaN,NaN,"<a href=""http://twitter.com/download/iphone"" r...",@Erostrate4ever @Medias24 Tu as tt dit 👌🏼,NaN
999999,NaN,148303071,NaN,950999070327410688,2018-01-10 07:53:41+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t950999070327410688,NaN,en,False,"{'retweet_count': 108, 'reply_count': None, 'l...",NaN,NaN,"<a href=""http://www.apple.com"" rel=""nofollow"">...","Open Access - why we need ""dangerous"" sport in...",NaN

In [ ]:
d.shape

(1300000, 17)

tweet_count

followers_count

following_count

followers_following_ratio

account_age_days

tweets_per_day

verified

description_length

url_ratio

hashtag_ratio

engagement_ratio